CREATE role admin_role;
CREATE role gerente_role;
CREATE role worker_role;
CREATE role app_role;

CREATE USER admin IDENTIFIED BY abcd1234;
CREATE USER gerente IDENTIFIED BY abcd1234;
CREATE USER worker IDENTIFIED BY abcd1234;
CREATE USER app IDENTIFIED BY abcd1234;

GRANT admin_role TO admin;
GRANT CREATE SESSION TO admin_role;
GRANT ALL PRIVILEGES TO admin_role;

GRANT gerente_role TO gerente;
GRANT CREATE SESSION TO gerente_role;
GRANT UPDATE ANY TABLE, SELECT ANY TABLE, INSERT ANY TABLE TO gerente_role;

GRANT worker_role TO worker;
GRANT CREATE SESSION TO worker_role;
GRANT SELECT ANY TABLE TO worker_role;
GRANT INSERT, UPDATE ON SYSTEM.CONTINGENCIA TO worker_role;
GRANT INSERT, UPDATE ON SYSTEM.MANTENIMIENTO TO worker_role;
GRANT INSERT, UPDATE ON SYSTEM.CUMPLE TO worker_role;
GRANT INSERT, UPDATE ON SYSTEM.HORARIO TO worker_role;

GRANT app_role TO app;
GRANT CREATE SESSION TO app_role;
grant SELECT ANY TABLE to app_role;
GRANT EXECUTE ON SYSTEM.REPORTE_12 TO app_role;

SELECT * FROM SYSTEM.CONTINGENCIA;
INSERT INTO SYSTEM.CONTINGENCIA (id, nombre, descripcion)
  VALUES (100,'Accidente','Accidente en la via');
UPDATE SYSTEM.CONTINGENCIA SET NOMBRE = 'Metiorito', DESCRIPCION = 'Ha caido una roca del cielo!' WHERE id = 100;
DELETE FROM SYSTEM.CONTINGENCIA WHERE id=100;
